name: BabelJockey
favicon: null
layout_spectrum: 0.90449
typography_spectrum: 0.24251
title: BabelJockey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d4d7c2'
    - '#95a8a4'
    - '#50401f'
    - '#8f6e4b'
  brandStrength: 0
  lightness: 0.6632880880497396
  saturation: 0.1875
  rhythmicContrast: 0.9455776324030012
purpose: []
