name: BabelJockey
favicon: null
layout_spectrum: 0.90927
typography_spectrum: 0.23819
title: BabelJockey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71609649-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d4d7c2'
    - '#95a8a4'
    - '#50401f'
    - '#8f6e4b'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
